ftp.go
Provides ability to resume transfer when uploading or downloading.
=> Add support for the REST command

client_test.go, ftp.go
=> Use JoinHostPort and SplitHostPort and for EPSV for IPv6

.travis.yml, .vsftpd.conf, README.md, client_test.go
You need add this project to [Travis CI](https://travis-ci.org/) to enable automatic builds.
Test results: https://travis-ci.org/digineo/ftp
=> Add Travis CI

client_test.go
This increases the test coverage from 57 to 83 %.
=> Test PASV as well

client_test.go, parse_test.go
Coverage increased (+2.8%) to 89.107%
=> Increase test coverage

client_multiline_test.go, client_test.go
This removes the dependency to ftp.mozilla.org
=> Create mock for multiline test

ftp.go
set utf8 on if server supported
=> use utf8 default

ftp.go
=> Switch to UTF-8 after login

ftp.go
=> ftp: fix OPTS UTF8 ON for Filezilla Server

client_test.go, ftp.go
=> Add SetDeadline to Response

client_test.go, ftp.go
Added the ability to remove folders recursively 
#81
=> added recursively deleting (non-empty) folders

ftp.go
=> Parse IP address returned with PASV to fix load balanced FTP servers

ftp.go, parse.go, parse_test.go
Needed to compare timestamps of files on a server running in AEST with local copies stored in UTC.
=> Make it possible to specify what timezone to parse timestamps in

ftp.go
I am working on adding support for implicit FTPS in Rclone. [Pull Request Here](https://github.com/ncw/rclone/pull/3150). This should complete implicit FTPS support. May still need a few changes.
=> Complete Implicit FTPS support

parse.go, parse_test.go
=> Support line with ACL permissions

ftp.go, parse.go, parse_test.go
=> Correctly parse symlink

ftp.go, walker.go, walker_test.go
This will allow the caller to traverse the directory tree of the remote server
=> Adds the ability to walk through a directory tree

client_test.go, conn_test.go, ftp.go
Hi, I am no expert regarding FTP, but I thought I could go ahead and add support for append/APPE. I have implemented this as close as possible to Stor and also had to make a small change to the ftpMock in order to include a test. My own test with a real FTP server gave a good result too.
=> Add support for FTP append (APPE) command

README.md
to make user able to go there easily without typing it
=> add documentation shortcut

ftp.go
See: https://tools.ietf.org/html/draft-dd-pret-00
Fixes #197
Note that this includes PR #201 - that should be merged first.
=> Implement PRET command for distributed ftp servers, eg drftpd

ftp.go
This PR fixes no bugs, but hopefully increases code clarity.
As per [Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters) it's a best practice to be explicit with return values, even when named return variables are used.
=> Remove naked returns

ftp.go
Before this change, uploading a zero length file via TLS meant that
the tls.Handshake function was never called.
ProFTPd quite properly refuses to accept an empty TCP connection with
no TLS handshake as a zero length upload and gives the error
425 Unable to build data connection: Operation not
See: https://forum.rclone.org/t/rclone-ftps-explicit-rclone-touch-empty-files-proftpd-unable-to-build-data-connection-operation-not-permitted/22522
=> Fix STOR of zero length files to ProFTPd with TLS
