jlaffaye/ftp

- ftp.go
Error Created in pasv() states EPSV rather than PASV
> Copy Paste Error / Typo

- ftp.go
The REIN command returned a StatusReady(220), not StatusLoggedIn, so calling the existing Logout was producing an error for me. Thanks for taking a look!
> Changing expected status response for Logout call

- .travis.yml
- README.md
To use coveralls.io, you need to connect it with you github account. The result looks like this:
https://coveralls.io/builds/3341978/source?filename=ftp.go
> Add coveralls.io to display test coverage

- ftp.go
- parse_test.go
I encountered an FTP server with yet another directory listing format. So I added support for it.
I also refactored the LIST line parsing code into separate functions, with a master function that calls the others one by one until one parses successfully.
> Add support for directory listings in MS-DOS DIR format.

- ftp.go
This results in less function calls.
> Avoid strings.Split

- ftp.go
I just had a crash with a server that returned an invalid pasv response, I don't really know how that happened since I've not been able to reproduce it (I don't manage the remote server).
> panic: runtime error: index out of range
goroutine 106 [running]:
github.com/jlaffaye/ftp.(*ServerConn).pasv(0xc821197d10, 0x0, 0x0, 0x0)
/home/etix/go/src/github.com/jlaffaye/ftp/ftp.go:201 +0x2b7
github.com/jlaffaye/ftp.(*ServerConn).openDataConn(0xc821197d10, 0x0, 0x0, 0x0, 0x0)
/home/etix/go/src/github.com/jlaffaye/ftp/ftp.go:229 +0x10e
github.com/jlaffaye/ftp.(*ServerConn).cmdDataConnFrom(0xc821197d10, 0x0, 0x8ef2b0, 0x7, 0xc8201db7f8, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
/home/etix/go/src/github.com/jlaffaye/ftp/ftp.go:258 +0x66
github.com/jlaffaye/ftp.(*ServerConn).List(0xc821197d10, 0xc820bf8030, 0xe, …
> Fix a crash with pasv invalid responses

- ftp.go
I'm not an expert in FTP protocol, maybe there are some better workarounds. I've faced an issue with third-party ftp server: EPSV is in the feature list, but EPSV connection could not be established, and currently library doesn't try to fallback to PASV in that case, and I was unable to use it.
This PR makes ServerConn::openDataConn() not to rely on the feature list sent by server, but to try opening both EPSV and PASV, and only if both fails return the error.
> ServerConn::openDataConn() recursively tries to use EPSV and PASV.

- ftp.go
- parse_test.go
The result of strings.Join(fields[8:], " ") is wrong if file name includes multiple spaces. We must get file name from original list line.
> Fix ls bug for file or folder name includes multiple spaces

- ftp.go
If the `REST` command fails the data connection needs to be closed.
> Add missing Close() before return

- ftp.go
- parse_test.go
When the file creation year, file size and filename contains the same substring the parsed filename should contains only the correct filename.
In the example below you can see the parsing fails in that case:
```
-rw-r--r--   1 marketwired marketwired    12016 Mar 16  2016 2016031611G087802-001.newsml
```
> Fix incorrect filename parsing

- client_test.go
- ftp.go
If we close the connection two times the second time will hang forever waiting for a server code.
> Avoid forever lock

- parse.go
- parse_test.go
This happened with one provider (hostedftp.com). Let me know if there's a better way to approach this problem.
> Add a case to catch Unix-like but 0 link count list line

- parse.go
- parse_test.go
This bug has been introduced by 4b298416eae16ab7b57c1a5eba86270a77165b72
closes #97
> Fix possible runtime error

- parse.go
- parse_test.go
The code should be able to fix #105 when a response from list returns lines with type formats starting with Uppercase.
> parseRFC3659ListLine issue

- ftp.go
If used DialWithNetConn, DialWithNetConn takes precedence for
the control connection, while data connections will be established
using function specified with the DialWithDialFunc option
> Add DialWithDialFunc to specify dial function used for both control and data connections

- .travis.yml
- go.mod
- go.sum
I have noticed that this library does not have a module definition yet, so I thought it might be time to add one.
This will probably fail at first in the Travis CI, because I could not think of any way to test if it works with the Travis build beforehand.
> Add Go module definition

- ftp.go
pure-ftpd 1.0.49-4 as supplied as part of Ubuntu 20.04 advertises UTF8
support in the FEAT command but the OPTS command fails to turn it on.
OPTS UTF8 ON
504 Unknown command
This patch introduces a workaround to ignore the error which enables
this library to work with this version of pure-ftpd. Filezilla appears
to ignore this error in a similar way.
> Workaround pure-ftpd connections failing with "Unknown command"

- ftp.go
This PR adds a `String()` function to the EntryType struct. `String()` returns the string representation of EntryType t.
Example:
```golang
// ...
w := conn.Walk("/")
for w.Next() {
fmt.Println(w.Stat().Type.String()) // => file, folder or link
}
```
> EntryType String() function

- walker.go
- walker_test.go
Previous version was trimming leading '/' from root path. It also wouldn't walk a directory that had one sole file inside.
> Rework walker.Next 

- ftp.go
if the upload failed we still need to try to read the server
response otherwise if the failure is not due to a connection problem,
for example the server denied the upload for quota limits, we miss
the response and we cannot use the connection to send other commands
Here is what happen before this patch:
C->S STOR test_file1.dat
S->C 150 Using transfer connection
S->C 550 Could not transfer file: denying write due to space limit
the client does not read the above 550 response and send the next command, so
the response for the STOR command will be readed as response for the next
command.
Full network traces here:
[traces.zip](https://github.com/jlaffaye/ftp/files/5002926/traces.zip)
> try to read the server response after a failed upload

- ftp.go
Some servers require the user to be logged in to run FEAT
ftp://serverftp:2121: Connecting to FTP server
FTP Rx: "220 DrFTPD+ 2.0 (+STABLE+) $Revision: 1949 $ http://drftpd.org"
FTP Tx: "AUTH TLS"
FTP Rx: "234 AUTH TLS successful"
FTP Tx: "FEAT"
FTP Rx: "530 Not logged in."
> Delay FEAT command until after Login - fixes #200

- ftp.go
This commit
4a68979b896a741e always return the ReadResponse error after an upload
Broke the error return from Stor().  If you attempt to upload a file
with Stor() and the io.Reader that you passed in returns an error,
this was not returned by the Stor() command leading the user to think
the file was uploaded correctly.
This was detected by rclone's unit tests and the exact commit was
pinpointed with git commit.
This commit fixes it by returning the error from io.Copy or the error
from ReadResponse - the latter if they are both set.
Fixes #198
> Fix Stor() no longer reporting errors from the io.Reader passed in

- ftp.go
This is useful for servers which advertise MLSD (eg some versions of
Serv-U) but don't support it properly.
> Add a DialWithDisabledMLSD option to ignore MLSD if advertised

- client_test.go
- conn_test.go
- ftp.go
Hi @jlaffaye 
We are using your great library as a filesystem backend in rclone.
A few rclone users hit a problem with Solaris FTP server, which was discussed in https://github.com/rclone/rclone/issues/1850
Namely, when they list contents of current remote directory, the ftp library concatenates the `LIST` (or `MSLD`) command
with an empty argument and sends `LIST  `   (with a trailing whitespace) out. Most FTP servers are fine with it but Solaris 
FTP replies with `500 Command not understood`. Removing the trailing whitespace fixes the situation for us.
In the first attempt I tried to strip edge whitespace generically on the `cmd` interface level but that resulted in errors.
In this patch I fix it only for `LIST`, `MSLD` and `NLST` commands leaving others as is.
Please approve.
Thank …
> trim trailing whitespace from the list commands

- ftp.go
Uploading of large files via this library and rclone frequently ends up with `i/o timeout`.
My investigation shows the following:
- `jlaffaye/ftp` makes control/data streams from a connection factory provided by rclone. This factory wraps standard go tcp streams in the [code](https://github.com/rclone/rclone/blob/v1.56.0/fs/fshttp/dialer.go#L85) which safeguards against silently dead network connections (lost without explicit TCP shutdown), namely cancels streams after timeout but resets timeout timer after each read/write.
- A typical FTP upload looks like: client talks with ftp server on control stream, sets upload parameters, then create one or more data streams and do the upload (this can be long), then return to control stream and ask ftp server about upload results  (here be …
> Nudge control connection deadline before reading the data closing status (Try 2)

- client_test.go
- conn_test.go
- ftp.go
The original FTP RFC had very limited support for file time which is inadequate nowadays. The `LIST` and `NLST` commands derived their time format directly from the Unix `ls` and provided time with 1sec resolution only for recent files but not for files older than a day. In fact, even getting precise timestamps was generally impossible. The `MLSD` extension partially improved situation, for directory listings. Later such extensions as `MDTM` and `MFMT` added protocol support for time setting and getting time on individual files to 1sec precision. The main FTP servers in use support them such as ProFTPd, PureFTPd, VsFTPd, Filezilla making FTP more suitable for modern development.
According to [RFC 3659](https://filezilla-project.org/specs/rfc3659.txt) the `MDTM` command can be used to get …
> Add SetTime command, related options and state getters

- walker.go
I believe you say: "Step" but mean "Next" since there is no Step()
function.
> Documentation update.

- ftp.go
This PR adds support for the ftp TYPE command to control the format used by the ftp server to transfer data. The new  function `Type(transferType TransferType)` enables switching between transfer types. Two constants for `TransferType` are defined, one for image/binary and one for ascii.
> support for the TYPE command

- client_test.go
- conn_test.go
- ftp.go
- parse.go
The `LIST` and `MLSD` commands are inefficient when the objective
is to retrieve one single `Entry` for a known path, because the only way
to get such an entry is to list the parent directory using a data
connection. The `MLST` fixes this by allowing one single `Entry` to be
returned using the control connection.
The name `Get` was chosen because it is often used in conjunction with
`List` as a mean to get one single entry.
Signed-off-by: Thomas Hallgren <thomas@datawire.io>
> Add MLST command in the form of a Get method

- client_test.go
- ftp.go
- walker.go
This is useful for servers that do not offer up
hidden folders/files by default when using LIST/MLSD
commands.
Setting forceListHidden to true will force the use of
the 'LIST -a' command even when MLST support has
been detected.
This is a fairly quick solution I put together to create a similar behaviour as FileZilla has when the option "Force showing hidden files" is enabled. I haven't created a build to test it yet but posting this early in case there is some fundamental flaw in my approach.
There is even an old stale issue that requested this: #136
> Add forceListHidden dial option to force the use of 'LIST -a' command

- ftp.go
In #282 it was discovered that doing the tls Handshake immediately on connection causes some FTP servers (proftpd and pureftpd) to hang.
The exact cause of this is unknown, but this patch works around the problem by not doing the Handsake initially, and only doing it at the end if we were attempting to upload a zero length file.
Doing the Handshake at the end was originally added in a4e9650823896675 however it got reverted in 212daf295f0e6ae4 which used tls.DialWithDialer to do the handshake. Unfortunately tls.DialWithDialer seems to trigger the hanging bug.
See: https://forum.rclone.org/t/rclone-ftps-explicit-rclone-touch-empty-files-proftpd-unable-to-build-data-connection-operation-not-permitted/22522
See: https://github.com/rclone/rclone/issues/6426#issuecomment-1243993039
Fixes #282
> Fix hang when using ExplicitTLS to certain servers.

- conn_test.go
- ftp.go
Some servers seem to send a blank line at the end of an MLST response.
MLST Download
250-
Size=53248;Modify=20230327134339.000;Type=dir; Download
250 Requested file action okay, completed.
Before this change this would cause the GetEntry method to return this error.
unsupported LIST line
This patch ignores blank lines in the MLST response.
> Fix GetEntry / MLST for some servers - Fixes #321

- ftp.go
- ftp_test.go
Some behind-firewall-and-corporate-network FTP servers responds their private-net address instead of the
publicly reachable.
This fix checks for such address and uses the
command channel's address instead.
> Fix PASV address like lftp does

- go.mod
Some Microsoft servers can return dates with a four-digit year format. This PR adds two new date formats to the `dirTimeFormats` variable in `parse.go` and also adds two new tests to `parse_test.go.
```
Four-digit years
Specifies the year format to use when displaying the last modified date for each file. If enabled, displays dates with four-digit years; otherwise, displays dates with two-digit years.
```
Microsoft ref : https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831403(v=ws.11)#feature-page-elements
> New date formats for non standard dates returned by LIST
